/* Configuration for libcurl generated by Alire */
#ifndef LIBCURL_CONFIG_H
#define LIBCURL_CONFIG_H

#define CRATE_VERSION "7.81.0"
#define CRATE_NAME "libcurl"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
